# Counting DNA Nucleotides
# s = "TCCCCTGAGTCATGGCGGTTCTGACATTAAATGGTTTTGGGGAGCTGCCCGATCTGTCAACCTCTGTCATGCCCAACCACACGGCGACAGTCCTACAGAGTCATGTCGTCCTGTGCACTGGCATCATTGGAGTACAAGCAAAGACCAGTCAGCAAGATCTTTTGATGATCAGCTACTATAGGCGTCGCTAAAGGTTTGGCGGTTACATTGGCTCAGTCGCGTATCACGGCCCAACGATAAAAAAAGAGGGTTGATTCAAGACTCATTGTTTTCGATAATCTGGGTTTAGAACCAAAGGTATGCCAGTTTGGTTTAGCAGAGTAACCAAAGCTGAATTATAGATATGTATATCACGGAGAGCCGATGTACATCGTTGGACCCACAGCAACGCGTGGGTCACTGCAGTCAACTGATAGCACCACCATATTGCAATATACCCTCAGCTGAGGTCCGCGAACGATGCGGGACCGCATCAATGCGAGCAAGTCTGTTTGGCAAGTCATTTCTCTGGTACTTTGGGTGTACATTGTTCCTTGGTTATAGAGAGGTTATGGAACCCAGGCACACTTTACTCGCGGTCTTTCAAGGTTTCGTAATCTCGTACCCGCGTGCTAGAAACCCGACTTAGAACATCAACCGCAGTCCCGCGGAATCGATTTCGATCGGGTACAGTCCGAGATGGCGACCGCCCGTCAAAGACCAGCGCCGGCAGCACTGAACATTTCATAAGTTGTGCCACTAGGCGTCAAACAGCCCTGATGACCATCTGGACAAAATATGGTACTGTTACGCGGTTAGTTCCTGTCTCGCATCTCAGGCCGTCGCCTTTGACCCATCCTTCGTACGTCCCTGTCGCACCAGACAGATATGGGGCGATGTCCCCTGATCTCATCTCGCCTATTGAGGGCCGTGGGAACGGGGAATACAAAGGATATA"

file = input("Input file name ")
fhand = open(file)
fout = open("result.txt", "w")
a = 0
t = 0
c = 0
g = 0

for line in fhand:
    for char in line:
        # print(char)
        if char == "A":
            a = a + 1
        elif char == "T":
            t = t + 1
        elif char == "C":
            c = c + 1
        elif char == "G":
            g = g + 1
        # else:
        #    print("error")

fout.write(str(a) + " " + str(c) + " " + str(g) + " " + str(t))
